services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticket-bot
    restart: unless-stopped
    environment:
      - RUN_MODE=bot
    volumes:
      - ./config:/app/config:rw
      - ./content:/app/content:rw
      - ./transcripts:/app/transcripts:rw
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
    networks:
      - ticket-bot-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticket-web
    restart: unless-stopped
    environment:
      - RUN_MODE=web
    ports:
      - "3050:3050"
    volumes:
      - ./config:/app/config:rw
      - ./content:/app/content:rw
      - ./transcripts:/app/transcripts:rw
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
    networks:
      - ticket-bot-network
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3050/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

networks:
  ticket-bot-network:
    driver: bridge
